#!/usr/bin/env python3
"""
Phase 52 — DISCRIMINATING HYPOTHESES
======================================

Post-Phase 51, we know:
  - Structure is character-level (z=80.3), NOT morphological (95.6% char-explained)
  - Vocabulary is anti-compositional (z=−25.4) under morphological decomposition
  - Can't distinguish natural from constructed language
  - Lines are syntactic units, left-to-right, gap-1 only

Phase 52 asks: what KIND of system produces these properties?
Five discriminating tests between natural language, cipher, and generation:

  52a) CHARACTER MODEL vs. LEXICON
       Can a character bigram model predict which words exist?
       If vocab is generated by character rules → clean separation.
       If vocab is a codebook → no clean separation.

  52b) WORD BURSTINESS
       Natural language words cluster (use once → use again soon).
       Codebook/cipher tokens are more uniformly distributed.
       Burstiness B>0 = natural, B≈0 = codebook, B<0 = mechanical.

  52c) WITHIN-LINE SURPRISAL CURVE
       Natural sentences: specific surprisal profile (high start, dip, rise).
       Encoding: flat or monotonic.

  52d) CHARACTER POSITIONAL ENTROPY
       H(char at position k within word) for k=1,2,...
       Natural language has specific patterns (consonant/vowel slots).
       Cipher/generated may be more uniform.

  52e) CHARACTER-LEVEL COMPOSITIONALITY (redo of 51d)
       Phase 51d used morphological decomposition (now known to be mostly
       character-level). Redo purely at character level: first-2 × last-2
       combinations. If vocabulary is compositionally generated at char
       level: high fill. If closed lexicon: low fill.
"""

import re, sys, io, math, random
from pathlib import Path
from collections import Counter, defaultdict
import numpy as np

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

random.seed(52)
np.random.seed(52)

ALL_GALLOWS = ['cth','ckh','cph','cfh','tch','kch','pch','fch',
               'tsh','ksh','psh','fsh','t','k','f','p']

def strip_gallows(w):
    temp = w
    for g in ALL_GALLOWS:
        while g in temp: temp = temp.replace(g, '', 1)
    return temp
def collapse_e(w): return re.sub(r'e+', 'e', w)
def get_collapsed(w): return collapse_e(strip_gallows(w))

FOLIO_DIR = Path("folios")

def load_lines():
    lines = []
    for fpath in sorted(FOLIO_DIR.glob("*.txt")):
        for line in fpath.read_text(encoding='utf-8', errors='replace').splitlines():
            line = line.strip()
            if line.startswith('#'): continue
            m = re.match(r'<([^>]+)>', line)
            rest = line[m.end():].strip() if m else line
            if not rest: continue
            words = [w.strip() for w in re.split(r'[.\s,;]+', rest)
                     if w.strip() and re.match(r'^[a-z]+$', w.strip())]
            if len(words) >= 2:
                lines.append(words)
    return lines

def compute_H(counts, total):
    H = 0.0
    for c in counts.values():
        if c > 0:
            p = c / total
            H -= p * math.log2(p)
    return H

print("Loading corpus...")
raw_lines = load_lines()
line_collapsed = [[get_collapsed(w) for w in line] for line in raw_lines]
all_collapsed = [w for seq in line_collapsed for w in seq]
N = len(all_collapsed)
vocab = Counter(all_collapsed)
word_types = set(vocab.keys())
n_types = len(word_types)
print(f"  {N} tokens, {n_types} types, {len(raw_lines)} lines\n")

# ============================================================
# 52a: CHARACTER MODEL vs. LEXICON
# ============================================================
print("=" * 65)
print("52a: CHARACTER MODEL vs. LEXICON")
print("=" * 65)

# Build character bigram model (with start/end markers)
char_bigram_counts = Counter()
char_unigram_counts = Counter()
for wtype in word_types:
    seq = '^' + wtype + '$'
    for i in range(len(seq) - 1):
        char_bigram_counts[(seq[i], seq[i+1])] += 1
        char_unigram_counts[seq[i]] += 1
    char_unigram_counts[seq[-1]] += 1

# Character bigram log-probability of a word
def char_bigram_logprob(word):
    seq = '^' + word + '$'
    lp = 0.0
    for i in range(len(seq) - 1):
        c1, c2 = seq[i], seq[i+1]
        bigram_c = char_bigram_counts.get((c1, c2), 0)
        ctx_c = char_unigram_counts.get(c1, 0)
        if bigram_c == 0 or ctx_c == 0:
            return -999.0  # impossible under model
        lp += math.log2(bigram_c / ctx_c)
    return lp

# Score all observed types
observed_scores = {}
for w in word_types:
    observed_scores[w] = char_bigram_logprob(w)

# Generate all possible words of lengths 2-7 using observed character set
# (excluding ^ and $)
chars_in_vocab = set()
for w in word_types:
    chars_in_vocab.update(w)
chars_list = sorted(chars_in_vocab)
print(f"  Alphabet: {len(chars_list)} characters: {''.join(chars_list)}")

# For efficiency, generate using the bigram model itself (only follow non-zero transitions)
def generate_words_by_bigram(max_len=7, max_words=200000):
    """Generate all words with non-zero bigram probability up to max_len."""
    words = set()
    # BFS from '^'
    stack = [('^', '')]  # (last_char, word_so_far)
    while stack and len(words) < max_words:
        last_c, prefix = stack.pop()
        for c2 in chars_list:
            if char_bigram_counts.get((last_c, c2), 0) > 0:
                new_word = prefix + c2
                if len(new_word) <= max_len:
                    # Check if this can end
                    if char_bigram_counts.get((c2, '$'), 0) > 0:
                        words.add(new_word)
                    if len(new_word) < max_len:
                        stack.append((c2, new_word))
    return words

print("  Generating all bigram-possible words (len 2-7)...")
possible_words = generate_words_by_bigram(max_len=7, max_words=500000)
print(f"  Generated {len(possible_words)} possible words")

# How many observed types are within this set?
observed_in_range = {w for w in word_types if 2 <= len(w) <= 7}
observed_and_possible = observed_in_range & possible_words
unobserved_possible = possible_words - word_types
print(f"  Observed types (len 2-7): {len(observed_in_range)}")
print(f"  Of these, bigram-possible: {len(observed_and_possible)} ({100*len(observed_and_possible)/max(1,len(observed_in_range)):.1f}%)")
print(f"  Unobserved but bigram-possible: {len(unobserved_possible)}")

# Score unobserved possible words
unobs_scores = []
for w in random.sample(list(unobserved_possible), min(50000, len(unobserved_possible))):
    s = char_bigram_logprob(w)
    if s > -999:
        unobs_scores.append(s)

obs_scores_list = [s for s in observed_scores.values() if s > -999]

print(f"\n  Log-probability statistics:")
print(f"    Observed:   mean={np.mean(obs_scores_list):.2f}, median={np.median(obs_scores_list):.2f}, "
      f"min={np.min(obs_scores_list):.2f}, max={np.max(obs_scores_list):.2f}")
print(f"    Unobserved: mean={np.mean(unobs_scores):.2f}, median={np.median(unobs_scores):.2f}, "
      f"min={np.min(unobs_scores):.2f}, max={np.max(unobs_scores):.2f}")

# What fraction of the top-k most probable possible words are observed?
all_possible_scored = []
for w in possible_words:
    s = char_bigram_logprob(w)
    if s > -999:
        all_possible_scored.append((s, w))
all_possible_scored.sort(reverse=True)

for k in [100, 500, 1000, 3000, 5000]:
    if k > len(all_possible_scored):
        break
    top_k = set(w for _, w in all_possible_scored[:k])
    obs_in_top_k = top_k & word_types
    print(f"    Top {k} most probable: {len(obs_in_top_k)} observed ({100*len(obs_in_top_k)/k:.1f}%)")

# Rank correlation: does probability predict frequency?
scored_observed = [(char_bigram_logprob(w), math.log2(vocab[w])) for w in word_types 
                   if char_bigram_logprob(w) > -999]
lp_arr = np.array([x[0] for x in scored_observed])
lf_arr = np.array([x[1] for x in scored_observed])
if len(lp_arr) > 10:
    rank_corr = np.corrcoef(lp_arr, lf_arr)[0, 1]
    print(f"\n  Correlation(char_bigram_logprob, log_freq) = {rank_corr:.3f}")
    print(f"  (Positive = high-prob words are high-freq = generative model)")
    print(f"  (Near zero = word freq independent of char model = codebook)")

# Selectivity: what fraction of bigram-possible words are actually observed?
selectivity = len(observed_and_possible) / max(1, len(possible_words))
print(f"\n  Lexicon selectivity: {selectivity:.4f} ({100*selectivity:.2f}%)")
print(f"  (Low selectivity = many possible words unused = constrained/codebook)")
print(f"  (High selectivity = most possible words used = generative)")


# ============================================================
# 52b: WORD BURSTINESS
# ============================================================
print("\n" + "=" * 65)
print("52b: WORD BURSTINESS")
print("=" * 65)

# Flatten all words in document order (within lines, lines in order)
flat_words = [w for line in line_collapsed for w in line]

# For top-N most frequent words, compute burstiness
top_words = [w for w, _ in vocab.most_common(100) if vocab[w] >= 20]
print(f"  Testing {len(top_words)} words with freq >= 20")

burstiness_results = []
for word in top_words:
    positions = [i for i, w in enumerate(flat_words) if w == word]
    if len(positions) < 10:
        continue
    gaps = [positions[i+1] - positions[i] for i in range(len(positions)-1)]
    mu = np.mean(gaps)
    sigma = np.std(gaps)
    B = (sigma - mu) / (sigma + mu)  # Goh & Barabasi burstiness
    burstiness_results.append((word, vocab[word], B, mu, sigma))

burstiness_results.sort(key=lambda x: -x[2])

print(f"\n  Burstiness B: (σ-μ)/(σ+μ)")
print(f"  B > 0: bursty (natural language)")
print(f"  B ≈ 0: Poisson (random/codebook)")
print(f"  B < 0: regular (mechanical)\n")

B_values = [x[2] for x in burstiness_results]
print(f"  Overall: mean B = {np.mean(B_values):.3f}, median B = {np.median(B_values):.3f}")
print(f"  Range: [{np.min(B_values):.3f}, {np.max(B_values):.3f}]")

bursty_count = sum(1 for b in B_values if b > 0.1)
poisson_count = sum(1 for b in B_values if -0.1 <= b <= 0.1)
regular_count = sum(1 for b in B_values if b < -0.1)
print(f"  Bursty (B>0.1): {bursty_count}/{len(B_values)} ({100*bursty_count/len(B_values):.0f}%)")
print(f"  Poisson-like (|B|<0.1): {poisson_count}/{len(B_values)} ({100*poisson_count/len(B_values):.0f}%)")
print(f"  Regular (B<-0.1): {regular_count}/{len(B_values)} ({100*regular_count/len(B_values):.0f}%)")

# Show top 10 most bursty and least bursty
print(f"\n  Top 10 most bursty words:")
for w, freq, B, mu, sigma in burstiness_results[:10]:
    print(f"    {w:15s}  freq={freq:5d}  B={B:+.3f}  μ_gap={mu:.1f}")
print(f"\n  Top 10 least bursty (most regular/Poisson):")
for w, freq, B, mu, sigma in burstiness_results[-10:]:
    print(f"    {w:15s}  freq={freq:5d}  B={B:+.3f}  μ_gap={mu:.1f}")

# Compare to Poisson null: for each word, generate Poisson gaps and compute B
print(f"\n  Poisson null comparison:")
null_B = []
for _ in range(1000):
    n_occ = random.choice([vocab[w] for w in top_words if vocab[w] >= 20])
    mean_gap = N / n_occ
    gaps = np.random.exponential(mean_gap, n_occ - 1)
    if len(gaps) > 1:
        mu = np.mean(gaps)
        sigma = np.std(gaps)
        null_B.append((sigma - mu) / (sigma + mu) if sigma + mu > 0 else 0)
print(f"  Poisson null: mean B = {np.mean(null_B):.3f}, median = {np.median(null_B):.3f}")
print(f"  VMS actual:   mean B = {np.mean(B_values):.3f}")
print(f"  Difference:   {np.mean(B_values) - np.mean(null_B):+.3f}")


# ============================================================
# 52c: WITHIN-LINE SURPRISAL CURVE
# ============================================================
print("\n" + "=" * 65)
print("52c: WITHIN-LINE SURPRISAL CURVE")
print("=" * 65)

# Unigram surprisal
total_tokens = sum(vocab.values())
unigram_prob = {w: c / total_tokens for w, c in vocab.items()}

# Bigram model (within lines)
bigram_counts = Counter()
bigram_ctx = Counter()
for line in line_collapsed:
    for i in range(len(line) - 1):
        bigram_counts[(line[i], line[i+1])] += 1
        bigram_ctx[line[i]] += 1

# Surprisal at each position for lines of length >= 5
max_pos = 12
unigram_surprisal_by_pos = defaultdict(list)
bigram_surprisal_by_pos = defaultdict(list)

for line in line_collapsed:
    if len(line) < 5:
        continue
    for i, w in enumerate(line):
        if i < max_pos:
            # Unigram surprisal
            p = unigram_prob.get(w, 1e-10)
            unigram_surprisal_by_pos[i].append(-math.log2(p))
            # Bigram surprisal (for i > 0)
            if i > 0:
                prev = line[i-1]
                bc = bigram_counts.get((prev, w), 0)
                cc = bigram_ctx.get(prev, 0)
                if bc > 0 and cc > 0:
                    bigram_surprisal_by_pos[i].append(-math.log2(bc / cc))
                else:
                    # Backoff to unigram
                    bigram_surprisal_by_pos[i].append(-math.log2(p))

print(f"  Unigram surprisal by word position (lines >= 5 words):")
print(f"  {'Pos':>4s}  {'Mean':>7s}  {'Std':>6s}  {'N':>6s}")
for pos in range(max_pos):
    vals = unigram_surprisal_by_pos[pos]
    if len(vals) > 50:
        print(f"  {pos+1:4d}  {np.mean(vals):7.3f}  {np.std(vals):6.3f}  {len(vals):6d}")

print(f"\n  Bigram surprisal by word position:")
print(f"  {'Pos':>4s}  {'Mean':>7s}  {'Std':>6s}  {'N':>6s}")
for pos in range(1, max_pos):
    vals = bigram_surprisal_by_pos[pos]
    if len(vals) > 50:
        print(f"  {pos+1:4d}  {np.mean(vals):7.3f}  {np.std(vals):6.3f}  {len(vals):6d}")

# Overall shape: is it declining (like natural language)?
means_uni = [np.mean(unigram_surprisal_by_pos[i]) for i in range(max_pos) 
             if len(unigram_surprisal_by_pos[i]) > 50]
if len(means_uni) >= 4:
    first_half = np.mean(means_uni[:len(means_uni)//2])
    second_half = np.mean(means_uni[len(means_uni)//2:])
    print(f"\n  Unigram surprisal: first half mean = {first_half:.3f}, second half = {second_half:.3f}")
    print(f"  Trend: {'DECLINING' if second_half < first_half else 'RISING' if second_half > first_half else 'FLAT'} "
          f"({second_half - first_half:+.3f} bits)")

means_bi = [np.mean(bigram_surprisal_by_pos[i]) for i in range(1, max_pos) 
            if len(bigram_surprisal_by_pos[i]) > 50]
if len(means_bi) >= 4:
    first_half = np.mean(means_bi[:len(means_bi)//2])
    second_half = np.mean(means_bi[len(means_bi)//2:])
    print(f"  Bigram surprisal:  first half mean = {first_half:.3f}, second half = {second_half:.3f}")
    print(f"  Trend: {'DECLINING' if second_half < first_half else 'RISING' if second_half > first_half else 'FLAT'} "
          f"({second_half - first_half:+.3f} bits)")


# ============================================================
# 52d: CHARACTER POSITIONAL ENTROPY
# ============================================================
print("\n" + "=" * 65)
print("52d: CHARACTER POSITIONAL ENTROPY")
print("=" * 65)

# H(char | position_in_word) for each position
max_char_pos = 10
char_at_pos = defaultdict(Counter)  # position -> char -> count
total_at_pos = Counter()

for w in all_collapsed:
    for i, c in enumerate(w):
        if i < max_char_pos:
            char_at_pos[i][c] += 1
            total_at_pos[i] += 1

print(f"  H(char | position) within words:")
print(f"  {'Pos':>4s}  {'H':>7s}  {'N_chars':>8s}  {'Top3':>30s}")
H_by_pos = []
for pos in range(max_char_pos):
    if total_at_pos[pos] < 100:
        break
    H = compute_H(char_at_pos[pos], total_at_pos[pos])
    H_by_pos.append(H)
    top3 = char_at_pos[pos].most_common(3)
    top3_str = ', '.join(f"{c}({100*n/total_at_pos[pos]:.0f}%)" for c, n in top3)
    print(f"  {pos+1:4d}  {H:7.3f}  {total_at_pos[pos]:8d}  {top3_str:>30s}")

# Compare: unconditional H(char)
all_chars = Counter()
for w in all_collapsed:
    for c in w:
        all_chars[c] += 1
total_chars = sum(all_chars.values())
H_unconditional = compute_H(all_chars, total_chars)
print(f"\n  Unconditional H(char) = {H_unconditional:.3f}")
print(f"  Mean H(char|pos) = {np.mean(H_by_pos):.3f}")
print(f"  Reduction: {H_unconditional - np.mean(H_by_pos):.3f} bits ({100*(H_unconditional - np.mean(H_by_pos))/H_unconditional:.1f}%)")

# Is the pattern consistent with phonotactic structure?
if len(H_by_pos) >= 3:
    print(f"\n  Position 1 H = {H_by_pos[0]:.3f} ({'LOW' if H_by_pos[0] < np.mean(H_by_pos) else 'HIGH'})")
    print(f"  Position 2 H = {H_by_pos[1]:.3f} ({'LOW' if H_by_pos[1] < np.mean(H_by_pos) else 'HIGH'})")
    if len(H_by_pos) > 2:
        print(f"  Position 3 H = {H_by_pos[2]:.3f} ({'LOW' if H_by_pos[2] < np.mean(H_by_pos) else 'HIGH'})")

# Mutual information between non-adjacent positions (skip-gram)
print(f"\n  Skip-gram MI within words (position i, position i+2):")
for gap in [2, 3]:
    mi_total = 0.0
    n_pairs = 0
    joint = Counter()
    marg1 = Counter()
    marg2 = Counter()
    for w in all_collapsed:
        if len(w) > gap:
            for i in range(len(w) - gap):
                if i < max_char_pos and i + gap < max_char_pos:
                    joint[(w[i], w[i+gap])] += 1
                    marg1[w[i]] += 1
                    marg2[w[i+gap]] += 1
                    n_pairs += 1
    if n_pairs > 0:
        mi = 0.0
        for (c1, c2), count in joint.items():
            p_joint = count / n_pairs
            p1 = marg1[c1] / n_pairs
            p2 = marg2[c2] / n_pairs
            if p_joint > 0 and p1 > 0 and p2 > 0:
                mi += p_joint * math.log2(p_joint / (p1 * p2))
        print(f"  Gap {gap}: MI = {mi:.4f} bits ({n_pairs} pairs)")


# ============================================================
# 52e: CHARACTER-LEVEL COMPOSITIONALITY
# ============================================================
print("\n" + "=" * 65)
print("52e: CHARACTER-LEVEL COMPOSITIONALITY")
print("=" * 65)

# Instead of morphological decomposition, use pure character edges
# For words of length >= 4, take first-2 and last-2 characters
# Test: what fraction of observed (first2, last2) combinations exist?

min_word_len = 4
long_types = [w for w in word_types if len(w) >= min_word_len]
print(f"  Word types with length >= {min_word_len}: {len(long_types)}")

first2_set = set()
last2_set = set()
observed_combos = set()

for w in long_types:
    f2 = w[:2]
    l2 = w[-2:]
    first2_set.add(f2)
    last2_set.add(l2)
    observed_combos.add((f2, l2))

total_possible = len(first2_set) * len(last2_set)
fill_rate = len(observed_combos) / total_possible if total_possible > 0 else 0

print(f"  Unique first-2 patterns: {len(first2_set)}")
print(f"  Unique last-2 patterns:  {len(last2_set)}")
print(f"  Total possible combos:   {total_possible}")
print(f"  Observed combos:         {len(observed_combos)}")
print(f"  Fill rate:               {fill_rate:.4f} ({100*fill_rate:.2f}%)")

# Compare to random expectation: if independently distributed, what fill rate?
# For M types from N_first2 × N_last2 cells: expected fill = N*(1-(1-1/N)^M)
N_cells = total_possible
M_types = len(long_types)
expected_fill = N_cells * (1 - (1 - 1/N_cells)**M_types) / N_cells if N_cells > 0 else 0
print(f"  Random expected fill:    {expected_fill:.4f} ({100*expected_fill:.2f}%)")

# Permutation test
n_perm = 1000
perm_fills = []
f2_list = [w[:2] for w in long_types]
l2_list = [w[-2:] for w in long_types]
for _ in range(n_perm):
    shuffled_l2 = random.sample(l2_list, len(l2_list))
    perm_combos = set(zip(f2_list, shuffled_l2))
    perm_fills.append(len(perm_combos) / total_possible)

perm_mean = np.mean(perm_fills)
perm_std = np.std(perm_fills)
z_fill = (fill_rate - perm_mean) / perm_std if perm_std > 0 else 0

print(f"  Permutation fill rate:   {perm_mean:.4f} ± {perm_std:.4f}")
print(f"  z-score:                 {z_fill:.1f}")
print(f"  Direction: {'ANTI-compositional (fewer combos than random)' if z_fill < -2 else 'COMPOSITIONAL (more combos than random)' if z_fill > 2 else 'CONSISTENT WITH RANDOM'}")

# Also test with first-1 × last-1 (single character edges)
print(f"\n  Single-character edge test (first-1 × last-1):")
for wlen_min in [3, 4, 5]:
    sel = [w for w in word_types if len(w) >= wlen_min]
    f1s = set(w[0] for w in sel)
    l1s = set(w[-1] for w in sel)
    obs_c = set((w[0], w[-1]) for w in sel)
    total_c = len(f1s) * len(l1s)
    fill_c = len(obs_c) / total_c if total_c > 0 else 0
    
    # Permutation test
    f1_list = [w[0] for w in sel]
    l1_list = [w[-1] for w in sel]
    pf = []
    for _ in range(1000):
        sl = random.sample(l1_list, len(l1_list))
        pf.append(len(set(zip(f1_list, sl))) / total_c)
    pm = np.mean(pf)
    ps = np.std(pf)
    zc = (fill_c - pm) / ps if ps > 0 else 0
    
    print(f"    len>={wlen_min}: {len(f1s)}×{len(l1s)}={total_c} cells, "
          f"fill={100*fill_c:.1f}%, perm={100*pm:.1f}%, z={zc:.1f}")


# ============================================================
# SYNTHESIS
# ============================================================
print("\n" + "=" * 65)
print("PHASE 52 SYNTHESIS")
print("=" * 65)

print("""
Key questions Phase 52 addressed:
1. Is the vocabulary generated by character-level rules, or is it a fixed list?
2. Do words cluster in usage (natural language) or distribute uniformly (codebook)?
3. Do lines have sentence-like information structure?
4. Are within-word character positions phonotactically constrained?
5. Is the vocabulary compositional at the character level (not just morphological)?

Implications for hypothesis discrimination:
- Natural language: expects burstiness, declining surprisal, phonotactic positional H
- Cipher/encoding: expects uniform burstiness, flat surprisal, uniform positional H  
- Mechanical generation: expects regularity, possibly cyclic patterns
""")

# Save output
output_path = Path("results/phase52_output.txt")
output_path.parent.mkdir(exist_ok=True)
print(f"\nPhase 52 complete. Run: python scripts/phase52_discriminators.py > results/phase52_output.txt")
